OpenRoberta/openroberta-lab

- RobotMbed/src/main/java/de/fhg/iais/roberta/visitor/validate/CalliopeSimValidatorVisitor.java
When you use certain calliope sensors, the wrong error message is displayed.
Bug fix 
- Create a new program
- Use the 'show text' block in association with the ultrasonic sensor/infrared sensor block.
- Run the simulation
As there was no implementation of the visitSensor methods of Infrared Sensor and Ultrasonic Sensor in CalliopeSimValidatorVisitor.java, the implementations of the respective methods in AbstractSimValidatorVisitor.java were used instead.
As a result the wrong error message was being displayed.
The visitUltrasonicSensor/visitInfrasonicSensor method was overriden in CalliopeSimValidatorVisitor.java and the appropriate error message was supplied.
**Behaviour prior to changes**
**Behaviour after changes**
> Fix for wrong Calliope error handling 

- RobotEV3/src/main/java/de/fhg/iais/roberta/visitor/codegen/Ev3StackMachineVisitor.java
When using the blocks from the message category, the user receives a server error.
Bug fix 
1. Create a new program
2. Create a connection variable and use it in association with a block from the messages Category.
3. Open the simulator
The default implementations of the VisitBluetoothAction methods were overriden in Ev3StackMachineVisitor.java.
> Fix for bluetooth blocks of EV3

- RobotMbed/src/main/java/de/fhg/iais/roberta/visitor/validate/MbedBoardValidatorVisitor.java
The wrong error message is displayed when the switch LED matrix block is used.
Bug fix
1. Create a new program under Calliope Mini.
2. Use the Switch LED matrix block.
3. Try to compile the code or open the source code view
The error message was coming from the implementation of the visitSwitchLedMatrixAction method in MbedBoardValidatorVisitor.java. The line switchLedMatrixAction.addInfo(NepoInfo.warning("SIM_BLOCK_NOT_SUPPORTED")); was removed.
> Removed wrong switch LED matrix warning

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/scene.js
When the RGB value from the colour sensor is printed, the range of values is from 0 - 100 instead of 0 - 255.
1. Create a new program
2. Use the 'show text' block with the 'get RGB colour' sensor block.
3. Start the simulation
The problem was being caused because the red, blue and green values from the sensor were being modified in scene.js to fit in the range of of 0 - 100 . These statements were changed such that the values are not modified.
> Fix for EV3 simulator colour sensor

- RobotNXT/src/main/java/de/fhg/iais/roberta/visitor/codegen/NxtStackMachineVisitor.java
When using the blocks from the 'messages' category, the user receives a server error.
Bug fix 
1. Create a new program in the NXT robot
2. Use a block from the 'messages' Category.
3. Open the simulator
The default implementations of the visitBluetoothSendAction, visitBluetoothCheckConnectAction, visitBluetoothReceiveAction and the visitConnectConst methods were overriden in NxtStackMachineVisitor.java.
> Fixed server error in NXT message blocks

- OpenRobertaServer/staticResources/js/app/roberta/controller/menu.controller.js
Fixed issue [#331](https://github.com/OpenRoberta/openroberta-lab/issues/331), tour now switches to ev3 bot.
> Fixed lab tour switching to ev3

- OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/codegen/ICompilerWorkflow.java
- OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/factory/RobotFactory.java
I've fixed three typos (acess -> access, compiles -> compiled, and impllementing -> implementing).
> Fix three typos in comments

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/robot.mbed.js
Fixed Issue #473. Not entirely sure why if(display.brightness) was not true when display.brightness was equal to 0 but adding this snippet of code fixes the issue.
> Fixed issue of setting the display to 0 brightness not working

- RobotWeDo/src/main/java/de/fhg/iais/roberta/visitor/validate/WedoBrickValidatorVisitor.java
**Description of issue**
When the 'buzzer' block in robot configuration is deleted and the 'play frequency' block is used,
the user receives a server error.
**Before Changes**
**After Changes**
> Fix for WeDo server error with empty port

- RobotEV3/src/main/java/de/fhg/iais/roberta/visitor/validate/Ev3SimValidatorVisitor.java
**Description**
The sound sensor does not show the unsupported message when used in the simulation
**Prior to changes**
**After changes**
> Add not supported message to sound sensor in EV3

- RobotEV3/src/main/java/de/fhg/iais/roberta/visitor/codegen/Ev3StackMachineVisitor.java
- RobotMbed/src/main/java/de/fhg/iais/roberta/visitor/codegen/MbedStackMachineVisitor.java
- RobotNXT/src/main/java/de/fhg/iais/roberta/visitor/codegen/NxtStackMachineVisitor.java
Fixed server error for the set variable block in Calliope, NXT, Microbit and EV3.
> Fix for empty set variable error

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/robot.nxt.js
Fixed EV3 robot's view appearing in NXT simulation, issue [#438](https://github.com/OpenRoberta/openroberta-lab/issues/438)
> Fixed EV3 robot view in NXT simulation

- RobotArdu/src/main/java/de/fhg/iais/roberta/visitor/validate/ArduinoBrickValidatorVisitor.java
The switch case is not being hit. 
The configuration block's component type does not match the case conditions: "INFRARED_SENSING" and "GYRO_SENSING". The component type does not have the "_SENSING" suffix. 
In the super method the switch statement works as the name attribute of the sensor matches the case clause. The super method has been called and the unnecessary code has been removed.
> issue #289 removed dead code

- RobotEdison/src/main/java/de/fhg/iais/roberta/visitor/collect/EdisonUsedHardwareCollectorVisitor.java
Fixed Issue #464 by generating definitions for values inside the parameters of the motion blocks.
Before Changes: <img alt="Screen Shot 2020-01-01 at 5 58 23 PM" width="1276" src="https://user-images.githubusercontent.com/9400738/71641363-b0d03700-2cc0-11ea-9cb9-f9fa4376277e.png">
After Changes:
> Fixed Edison IRSeeker Compiler Error

- OpenRobertaServer/staticResources/js/app/roberta/controller/progList.controller.js
Fixed issue #293 
After Changes: 
The problem was that both the dropdown list and row were registered as clicked, so both actions occurred simultaneously.
This have been solved by only allowing the top-most click to go through and afterwards manually toggling the collapse.
> Show sharee dropdown

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js
Fixes issue #612 
The up key will allow the robot to continue forward in its current direction, and the down key will allow the robot to move backwards in the current direction
Here's a video showing the process:
> Allow up and down arrows to move robot

- RobotEV3/src/test/resources/syntax/code_generator/java/java_code_generator12.xml
- RobotEdison/src/test/resources/syntax/actor/tone_action.xml
Fixed some formatting errors in xml files.
There have also been some redundant blocks in some of the xml files, such as an extra math "0" block hanging around, not attached to the actual program. 
For different robots, the indent spacing is different (ev3 has 2 spaced indents, while edison xml files have 4 spaced indents). Is this done purposely?
> Fix formatting for xml test

- README.md
Links to the Eclipse and IntelliJ setups have been added to the ReadME.
This is a fix for issue #692
> Added Links in README for Setups

- README.md
The given link in 'javascript resources for blockly' is not correct So changed the link.
> Changed Link for Blockly!

- RobotEV3/src/main/java/de/fhg/iais/roberta/javaServer/restServices/robot/ev3/ev3dev/Update.java
- RobotEV3/src/main/resources/ev3dev.properties
It is still disabled until we have an ev3dev image containing a 1.7.5
version out.
See #730
> Add server side support for updating ev3dev updates.

- OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/visitor/lang/codegen/prog/AbstractJavaVisitor.java
- RobotEV3/src/test/java/de/fhg/iais/roberta/syntax/expr/LogicExprTest.java
fixes #763
I have updated the Java Visitor to always enclose a test block (i.e. ternary expression) inside parentheses. Additionally, the Logical Expression test has also been modified to include parentheses around the ternary expression.
This is my first contribution, please let me know if you have any feedback!
> Test block paranthesis

- README.md
Section introduction: typo in installation instruction for Edison and Bionics4Education
Section remarks about the database: small typo correction
> Fix: typo in readme

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js
fixed resetting the outline of objects: initScene() and resizeAll() called the scene methods drawObstacles() and drawColoredAreas() with the same value for highlightCorners, so even only e.g an obstacle is selected it would draw the outlines for a coloredArea
> issue#1013 fixed resetting the outline of objects

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js
Removed robotModal.off() from removeMouseEvents() so its always interactable when visible. This works for all robots.
> Fix issue #899 ev3 image (for show text, ...) frozen after sim run

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/scene.js
instead of zero decimal places, the debug mode displays values of variables with up to 2 decimal places now
> issue #1017 debug mode now displays values with up to 2 decimal places

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/scene.js
This PR removes the objects that get created in the multiple robot simulation if it returns to a single robot simulation.
> issue #557 removing Robot select if there is only one robot

- OpenRobertaServer/staticResources/index.html
When Selecting multiple programs for the simulation, the selection table now remembers which programs are selected when changing the page. Therefore its now possible to run Robots from different pages in the multiple robot simulation.
> Part of Issue#861 , MultipleRobotsTable now remembers selected Program

- OpenRobertaServer/staticResources/js/app/roberta/controller/menu.controller.js
the default browser shortcuts weren't prevented.
deleted second Ctrl+E.
the ascii converter isn't necessary, changed it to e.which == Ascii code
> issue #1058 added preventDefault, changed String.fromCharCode to just e.which

- OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/syntax/SC.java
- OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/visitor/validate/DifferentialMotorValidatorAndCollectorVisitor.java
- OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/visitor/validate/MotorValidatorAndCollectorVisitor.java
- RobotEV3/src/main/java/de/fhg/iais/roberta/visitor/validate/DifferentialMotorValidatorAndCollectorVisitorEv3.java
- RobotEV3/src/main/java/de/fhg/iais/roberta/visitor/validate/Ev3ValidatorAndCollectorVisitor.java
Also added DifferentialMotorValidatorAndCollectorVisitor for new configurations and moved old DifferentialMotorValidatorEV3 to the EV3 plugin.
This change is important for the validators of new robot Systems with the new configuration, which use a differential drive block  at the moment that is mBot2 and ORB.
Refactor
Tested EV3 validators as its the only system that should be affected, also successfully ran Integration tests.
It is also used in  the feature/mBot2 branch without any issues.
> Refactored heritage structure of MotorValidatorAndCollectorVisitor 

- OpenRobertaServer/staticResources/js/app/nepostackmachine/interpreter.state.js
- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/robot.ev3.js
- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js
- OpenRobertaWeb/src/app/nepostackmachine/interpreter.state.ts
- OpenRobertaWeb/src/app/simulation/simulationLogic/robot.ev3.js
- OpenRobertaWeb/src/app/simulation/simulationLogic/simulation.js
* Replace Array.from() with spread syntax.
* Replace dynamic imports with require() and callback.
* Add simEditButtons to list of divs to be shown in case of IE.
* Add else block for SpeechSynthesis.cancel().
Note: Array.from() and dynamic imports (which return a Promise object) are not compatible with IE. Transpiled ts code was thus erroneous for use with IE.
Fixes #1195 
Tested on Internet Explorer 11 on following (remote) Windows machines:
- Windows 7
- Windows 8.1
- Windows 10
> #1195: Fix simulation not working on IE 11

- OpenRobertaServer/staticResources/js/app/nepostackmachine/interpreter.robotSimBehaviour.js
- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/robot.ev3.js
- OpenRobertaWeb/src/app/nepostackmachine/interpreter.robotSimBehaviour.ts
- OpenRobertaWeb/src/app/simulation/simulationLogic/robot.ev3.js
This PR fixes the following issues:
- A zero for the tone-block duration parameter would end in an infinite loop in the simulation
- An empty string for the sayText-block parameter would end in an infinite loop in the simulation
The problem was, when executing these blocks the next operation gets blocked from execution so the tone-/sayText-block could finish, but a zero or an empty string as a parameter wasn't handled correctly. 
Now the further code execution only gets blocked when the tone-Block Parameter is > 0 and the sayText-block parameter isn't an empty string.
> Issue #1187: tone-block and sayText-block won't stop further code execution

- OpenRobertaServer/src/main/java/de/fhg/iais/roberta/javaServer/restServices/all/ServerData.java
- admin.bat
Add support for tutorial-editor to access server through REST endpoints.
- add REST endpoints:
- /robot/whitelist: get robots used by the server.
- /robot/xml?robotName=<robot>: get XML data for a robot.
- fixed paths in admin.bat for use on Windows systems.
Fixes #1193 
Generate a local release `openrobertalab_binaries` and follow the usage guidelines [mentioned here](https://github.com/OpenRoberta/robertalab-tutorial-editor/blob/develop/README.md).
The corresponding changes to the tutorial editor can be [found here](https://github.com/OpenRoberta/robertalab-tutorial-editor/tree/develop).
Tested on:
- Windows (Chrome)
- Ubuntu (Chrome, Firefox)
> Issue #1193: integrate lab with tutorial editor

- OpenRobertaServer/staticResources/help/progHelp_arduino_de.html
- OpenRobertaServer/staticResources/help/progHelp_arduino_en.html
- OpenRobertaServer/staticResources/help/progHelp_bob3_de.html
- OpenRobertaServer/staticResources/help/progHelp_calliope_de.html
- OpenRobertaServer/staticResources/help/progHelp_calliope_en.html
- OpenRobertaServer/staticResources/help/progHelp_edison_de.html
- OpenRobertaServer/staticResources/help/progHelp_edison_en.html
- OpenRobertaServer/staticResources/help/progHelp_ev3_de.html
- OpenRobertaServer/staticResources/help/progHelp_ev3_en.html
- OpenRobertaServer/staticResources/help/progHelp_festobionic_de.html
- OpenRobertaServer/staticResources/help/progHelp_mbot_de.html
- OpenRobertaServer/staticResources/help/progHelp_mbot_en.html
- OpenRobertaServer/staticResources/help/progHelp_microbit_de.html
- OpenRobertaServer/staticResources/help/progHelp_microbit_en.html
- OpenRobertaServer/staticResources/help/progHelp_nano33ble_de.html
- OpenRobertaServer/staticResources/help/progHelp_nano33ble_en.html
- OpenRobertaServer/staticResources/help/progHelp_nao_de.html
- OpenRobertaServer/staticResources/help/progHelp_nao_en.html
- OpenRobertaServer/staticResources/help/progHelp_nxt_de.html
- OpenRobertaServer/staticResources/help/progHelp_nxt_en.html
- OpenRobertaServer/staticResources/help/progHelp_sensebox_de.html
- OpenRobertaServer/staticResources/help/progHelp_sensebox_en.html
- OpenRobertaServer/staticResources/help/progHelp_wedo_de.html
- OpenRobertaServer/staticResources/help/progHelp_wedo_en.html
Add an indicator to the block help texts if a block internally clippes the input value. This is done by a simple sentence for the input variable that will be clipped.
Fixes #145 
This has been tested locally by looking at the help texts in both English and German.
- [] I have commented my code, particularly in hard-to-understand areas
> Issue #145: add indicator to block help for clipping

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js
- OpenRobertaWeb/src/app/simulation/simulationLogic/simulation.js
A running rendering of a simulation is now always canceled before starting a new one.
New frames are only requested after the pending frame is fully rendered.
Fixes #556 
- Bug fix (non-breaking change which fixes an issue)
- maven integration Tests
- visual tests in the lab
> Issue #556: invisible simulations are canceled  

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js
- OpenRobertaServer/staticResources/js/app/webotsSimulation/webots.simulation.js
- OpenRobertaWeb/src/app/simulation/simulationLogic/simulation.js
- OpenRobertaWeb/src/app/webotsSimulation/webots.simulation.ts
**This PR fixes following problems:**
- simRobot and simValue buttons appear again when switching from Nao-sim to another robot-sim
- simResetPose button appears again when switching from calliope/microbit-sim to Nao-sim
> Issue #1186: buttons in simulations appear like they should

- OpenRobertaServer/staticResources/js/app/roberta/controller/progRun.controller.js
- OpenRobertaWeb/src/app/roberta/controller/progRun.controller.js
- RobotArdu/src/main/java/de/fhg/iais/roberta/worker/NIBOResetFirmwareWorker.java
- RobotArdu/src/main/java/de/fhg/iais/roberta/worker/transfer/NIBOTransferWorker.java
- RobotArdu/src/main/resources/bob3.properties
- RobotArdu/src/main/resources/rob3rta.properties
- update Bob3TransferWorker to get encoded hex of the factory default program for reset requests.
- update progRun.controller::reset2DefaultFirmware() to transfer program for arduinoAgentOrToken connection robots.
Fixes #1254 
Tested on affected NIBO robots (Bob3, Rob3rta).
For each robot:
- Connected robot to computer.
- Clicked on "reset to factory defaults".
- Checked whether robot is programmed as expected.
> Issue #1254: fix function "reset to factory defaults" for robots with arduinoAgentOrToken connection.

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js
- OpenRobertaWeb/src/app/simulation/simulationLogic/simulation.js
This **PR** fixes the issues stated in the OpenRoberta-Lab Issue #1160: 
- the defaultObstacle only gets set when sim is started for the first time or the background is changed (not when the roboter is changed)
- obstacles, colorAreas and background are saved when switching from a robot simulation (ev3, nxt, mBot) to the calliope/microbit simulation, so that when switching back to a ev3, nxt, mBot, the obstacles, colorAreas and the background from before are loaded.
> Issue #1160: defaultObstacle stays deleted when toggling the sim + more

- OpenRobertaServer/staticResources/css/roberta.css
- OpenRobertaServer/staticResources/index.html
- OpenRobertaServer/staticResources/js/app/roberta/controller/guiState.controller.js
- OpenRobertaServer/staticResources/js/app/roberta/controller/progSim.controller.js
- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/constants.js
- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js
- OpenRobertaServer/staticResources/js/helper/util.js
- OpenRobertaWeb/src/app/roberta/controller/guiState.controller.js
- OpenRobertaWeb/src/app/roberta/controller/progSim.controller.js
- OpenRobertaWeb/src/app/simulation/simulationLogic/constants.js
- OpenRobertaWeb/src/app/simulation/simulationLogic/simulation.js
- OpenRobertaWeb/src/helper/util.js
Previously The robot and variable simulation windows were modals which caused an issue where the simulation would scroll out of the window/ disappear when one of those windows was partially out of frame while opening another.
This is now fixed by having them not be modals anymore.
This PR also changes a bunch of other things to the behavior of those two windows for convinience and to stop them from moving out of the window.
Effects:
- RobotWindows no longer make the simulation disappear when out of the window,
- simRobotModal now has a max height,
- RobotWindows now have a different animation when the simulation is closed compared to using the toggle button,
- RobotWindows no longer show up in front of error messages and warning modals,
- Is no longer in the class .modal, but it's now …
> Issue #1188: Robot and Variable Simualtion Window are no longer modals

- RobotNAO/src/main/resources/simulation/protos/Roughcast.proto
- RobotNAO/src/main/resources/simulation/protos/textures/roughcast/README.md
This PR should fix the missing roughcast.png texture file as displayed by the browser:
> Fixes the missing roughcast.png file

- RobotArdu/src/main/java/de/fhg/iais/roberta/visitor/validate/MbotSimValidatorAndCollectorVisitor.java
- RobotEV3/src/main/java/de/fhg/iais/roberta/visitor/validate/Ev3SimValidatorAndCollectorVisitor.java
- RobotNAO/src/main/java/de/fhg/iais/roberta/visitor/validate/NaoSimValidatorAndCollectorVisitor.java
- RobotNXT/src/main/java/de/fhg/iais/roberta/visitor/validate/NxtSimValidatorAndCollectorVisitor.java
for blocks that are not supported in the the simulation
in the systems Ev3, Mbot, Nao and Nxt
most simValidatorAndCollectorVisitors only threw warnings if a block was not supported. This causes issues when a sensor block is used together with a supported action block. 
All blocks that can be used with a variable or an action block now cause errors instead of warnings
Fixes #1344
> Adjusted simValidators to show erros when necessary 

- RobotNAO/src/main/java/de/fhg/iais/roberta/visitor/codegen/NaoPythonSimVisitor.java
Fixes wrong bracket placement for visistRgbColor visit-Method in the NAO SIM python code generation.
This was already fixed for the NAO-Python generator but not for the simulation. The naoColour_rgb block now works as expected in the simulation.
Fixes #1339
> Fixing bracket placement for naoCalour_rgb block in the simulation.

- OpenRobertaServer/staticResources/js/app/roberta/controller/program.controller.js
- OpenRobertaWeb/src/app/roberta/controller/program.controller.js
* fix missing parameters in showSourceProgram call in programToBlocklyWorkspace function.
Tested locally, Error is not logged with the changes implemented.
> Issue #1373: fix error logged after changing the robot

- OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/mbot2/action.py
- OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/mbot2/sensors.py
- OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/mbot2/text_colours_functions.py
- RobotCyberpi/src/main/java/de/fhg/iais/roberta/visitor/Mbot2Methods.java
- RobotCyberpi/src/main/java/de/fhg/iais/roberta/visitor/Mbot2PythonVisitor.java
- RobotCyberpi/src/main/resources/helperMethodsMbot2.yml
- RobotCyberpi/src/main/resources/mbot2.properties
- This PR changes the calculation for the time it takes the mBot2 to travel a certain distance given the speed of each wheel.
- The methods have been adjusted to be more readable
- Division by zero gets caught to avoid runtime Errors
There are also two minor changes in this PR
- The Mbot2 no longer has the robot menu option to setup Wi-fi 
-  Acceleration sensor used 9,8 instead of 9.8 causing runtime errors this has been replaced
- Integrationstests have been adjusted and tested
- Tested on the real robot using the connector program with different combinations of speeds and distances
> Issue/1440 Fix DivisionByZero DiffDriveFor + minor changes

- OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/robot.actuators.js
- OpenRobertaWeb/src/app/simulation/simulationLogic/robot.actuators.ts
For Issue 1414, it is required for the robotino robot to abort blocking blocks (This applies to the drive: x, y, distance and the drive to: x, y, speed, block) commands in case of collision.
> Issue #1414: Stop Robotino when colliding
