Docker/openroberta/conf/docker-for-lab/start.sh
RobotEV3/src/main/java/de/fhg/iais/roberta/components/ev3c4ev3/Uf2Builder.java
RobotEV3/src/main/java/de/fhg/iais/roberta/components/ev3c4ev3/Uf2FileContainer.java

First pull request

---

OpenRobertaServer/src/main/java/de/fhg/iais/roberta/javaServer/restServices/all/controller/ClientUser.java
OpenRobertaServer/src/main/java/de/fhg/iais/roberta/main/Administration.java
OpenRobertaServer/src/main/java/de/fhg/iais/roberta/main/ServerStarter.java

Fixed three typos in code comments.

Fixed typos in comments

---

RobotEV3/src/main/java/de/fhg/iais/roberta/javaServer/restServices/robot/ev3/lejos/v0/Update.java
RobotRaspberryPi/src/main/java/de/fhg/iais/roberta/components/raspberrypi/RaspberryPiCommunicator.java
RobotRaspberryPi/src/main/java/de/fhg/iais/roberta/visitor/collect/RaspberryPiUsedHardwareCollectorVisitor.java
RobotVorwerk/src/main/java/de/fhg/iais/roberta/components/vorwerk/VorwerkCommunicator.java

Fixed minor typos within the code as a part of the task "First pull request (Programming Getting Started 2/2)."

Fixed minor typos within the code

---

RobotEV3/src/main/java/de/fhg/iais/roberta/visitor/codegen/Ev3JavaVisitor.java
RobotEV3/src/test/java/de/fhg/iais/roberta/syntax/codegen/ev3/Ast2C4ev3VisitorTest.java
RobotEV3/src/test/java/de/fhg/iais/roberta/syntax/codegen/ev3/AstToEv3PythonVisitorTest.java
RobotEV3/src/test/java/de/fhg/iais/roberta/syntax/codegen/ev3/AstToLejosJavaVisitorTest.java
RobotEV3/src/test/resources/syntax/code_generator/java/java_code_generator12.xml

Added resetTimer() and getValueTimer() test to each of the three platforms. Fixed #399.

Add Ev3 Timer Tests and remove StringOutOfBoundsException

---

OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/transformer/AbstractJaxb2Ast.java
OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/util/Pair.java
OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/util/Util.java

fixed three typos.

---

OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/scene.js
OpenRobertaServer/staticResources/js/helper/util.js

Fixed issue with inconsistency with the displayed ultrasound value

---

OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js

Fixed flickering button during background upload, issue [#391](https://github.com/OpenRoberta/openroberta-lab/issues/391)

Fixed button flickering during background upload

---

OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/visitor/validate/AbstractProgramValidatorVisitor.java

Prior to changes
After changes

Fix for wrong error when motors are removed

---

OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js

Fixed issue [#553](https://github.com/OpenRoberta/openroberta-lab/issues/553) where some robots appeared offscreen.
Before, with 9 robots:
After:

Fixed robots appearing offscreen in multiple simulation

---

OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/factory/IRobotFactory.java
OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/factory/RobotFactory.java
OpenRobertaServer/src/main/java/de/fhg/iais/roberta/javaServer/restServices/all/controller/ClientInit.java
OpenRobertaServer/staticResources/js/app/roberta/controller/guiState.controller.js
OpenRobertaServer/staticResources/js/app/roberta/controller/menu.controller.js
RobotArdu/src/main/resources/bob3.properties
RobotArdu/src/main/resources/botnroll.properties
RobotArdu/src/main/resources/festobionic.properties
RobotArdu/src/main/resources/mbot.properties
RobotArdu/src/main/resources/mega.properties
RobotArdu/src/main/resources/nano.properties
RobotArdu/src/main/resources/sensebox.properties
RobotArdu/src/main/resources/uno.properties
RobotArdu/src/main/resources/unowifirev2.properties
RobotEV3/src/main/resources/ev3c4ev3.properties
RobotEV3/src/main/resources/ev3dev.properties
RobotEV3/src/main/resources/ev3lejosv0.properties
RobotEV3/src/main/resources/ev3lejosv1.properties
RobotEdison/src/main/resources/edison.properties
RobotMbed/src/main/resources/calliope2016.properties
RobotMbed/src/main/resources/calliope2017.properties
RobotMbed/src/main/resources/calliope2017NoBlue.properties
RobotMbed/src/main/resources/microbit.properties
RobotNAO/src/main/resources/nao.properties
RobotNXT/src/main/resources/nxt.properties
RobotRaspberryPi/src/main/resources/raspberrypi.properties
RobotVorwerk/src/main/resources/vorwerk.properties
RobotWeDo/src/main/resources/wedo.properties

issue #582 revise robot information in welcome screen at german/english website where possible issue #579 robot calliope has icon “i“

---

OpenRobertaServer/staticResources/js/app/roberta/controller/notification.controller.js
TypeScriptSources/README.md
TypeScriptSources/package-lock.json
TypeScriptSources/package.json
TypeScriptSources/ts/app/roberta/controller/notification.controller.ts

I reworked the notification controller with an object oriented approach.

Migrate notification controller to Typescript

---

OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/robot.ev3.js
OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/robot.nxt.js

This PR fixes issue #439 it now applies volume where needed, also the file block now works and the sayText feature works in Chrome.

Fix for #439 - Volume not applying to tone

---

OpenRobertaServer/staticResources/js/app/roberta/controller/multSim.controller.js

This PR fixes the problem that you couldn't execute several programs with the same name, even though they had different creators

issue #853 multiple simulation will now execute all selected programs 

---

OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/robot.calliope.js
OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/robot.mbed.js

issue #583: Gestures now in the same order for Calliope and mbed/Micro:bit

---

OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js

highlights will be set on the correct layer now, when changing the color of objects

changing color of objects now highlights correct layer

---

OpenRobertaServer/staticResources/js/app/roberta/controller/progSim.controller.js
OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/simulation.js

this is V1 of the mentioned Versions, meaning when the program is finished the stop button disappears and the play button turns into the stop button.

issue #997 Calliope Start/Stop buttons in Debugging Tab now less confusing

---

OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/visitor/lang/codegen/AbstractStackMachineVisitor.java
OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/visitor/lang/codegen/JumpLinker.java
OpenRobertaRobot/src/test/java/de/fhg/iais/roberta/visitor/lang/codegen/JumpLinkerTest.java
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/common/astGenerated/controlFlowNestedLoops.ast
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/common/stackmachineLanguage/controlFlowNestedLoops.json
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/common/targetLanguage/calliope2017NoBlue/controlFlowNestedLoops.cpp
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/common/targetLanguage/ev3dev/controlFlowNestedLoops.py
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/common/targetLanguage/ev3lejosv1/controlFlowNestedLoops.java
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/common/targetLanguage/wedo/controlFlowNestedLoops.json
OpenRobertaServer/src/test/resources/crossCompilerTests/common/prog/controlFlowNestedLoops.xml

Fix #1047 by extract linking of jumps into a class responsible for this.

Extract Jump Linking into separate class

---

OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/scene.js
OpenRobertaWeb/src/app/simulation/simulationLogic/scene.js

This PR adds variables to the simulation sensor-data view

Issue #1156: simulation sensor-data view shows variables

---

OpenRobertaServer/staticResources/js/app/roberta/controller/progSim.controller.js
OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/robot.calliope.js
OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/robot.mbed.js
OpenRobertaServer/staticResources/js/app/simulation/simulationLogic/scene.js
OpenRobertaWeb/src/app/roberta/controller/progSim.controller.js
OpenRobertaWeb/src/app/simulation/simulationLogic/robot.calliope.js
OpenRobertaWeb/src/app/simulation/simulationLogic/robot.mbed.js
OpenRobertaWeb/src/app/simulation/simulationLogic/scene.js

implemented adjustable temperaturesensor and a validator for the sensorinput in the simulation.
Adjusted lightsensor and compasssensor

issue #964 adjustable temperaturesensor for calliope/microbit

---

OpenRobertaServer/staticResources/js/app/roberta/controller/guiState.controller.js
OpenRobertaServer/staticResources/js/app/roberta/controller/progSim.controller.js
OpenRobertaServer/staticResources/js/app/roberta/controller/robot.controller.js
OpenRobertaServer/staticResources/js/app/webotsSimulation/webots.simulation.js
OpenRobertaServer/staticResources/js/helper/util.js
OpenRobertaWeb/src/app/roberta/controller/guiState.controller.js
OpenRobertaWeb/src/app/roberta/controller/progSim.controller.js
OpenRobertaWeb/src/app/roberta/controller/robot.controller.js
OpenRobertaWeb/src/app/webotsSimulation/webots.simulation.ts
OpenRobertaWeb/src/helper/util.js

**This PR fixes following problems:**
- The right-view (code-view, sim-view, etc.) didn't close before switching robots, that lead to problems with the NAO-simulation
- The NAO-simulation did not disconnect from the server when not manually closing the simulation-view
**Now:**
- When switching robots, the right-view closes before the robot is switched
- The Nao-simulation disconnects whenever the right-view is closed

Issue #1247: Nao-Sim disconnects and right-view closes before switching robots

---

OpenRobertaServer/staticResources/help/progHelp_festobionicflower_de.html
OpenRobertaServer/staticResources/help/progHelp_festobionicflower_en.html
OpenRobertaServer/staticResources/help/progHelp_rob3rta_de.html
OpenRobertaServer/staticResources/help/progHelp_rob3rta_en.html

Added helptexts for the robot systems rob3rta and festobionicflower and improved helptexts for bob3
Tested with local installation of Open Roberta Lab on Windows 10.

add helptexts for bob3, rob3rta and bionicflower

---

OpenRobertaServer/staticResources/help/progHelp_xNN_de.html
OpenRobertaServer/staticResources/help/progHelp_xNN_en.html

Issue #1307 :add helptexts for xNN system
add helptexts for Open Roberta xNN robot system.
Fixes # (issue)
tested locally on my windows 10 machine

Issue #1307: add helptexts for xNN

---

OpenRobertaServer/staticResources/help/progHelp_arduino_de.html
OpenRobertaServer/staticResources/help/progHelp_arduino_en.html
OpenRobertaServer/staticResources/help/progHelp_bob3_de.html
OpenRobertaServer/staticResources/help/progHelp_bob3_en.html
OpenRobertaServer/staticResources/help/progHelp_ev3_de.html
OpenRobertaServer/staticResources/help/progHelp_ev3_en.html
OpenRobertaServer/staticResources/help/progHelp_nxt_de.html
OpenRobertaServer/staticResources/help/progHelp_nxt_en.html
OpenRobertaServer/staticResources/help/progHelp_rob3rta_de.html
OpenRobertaServer/staticResources/help/progHelp_rob3rta_en.html

Added various improvements and corrections to the help texts of ev3, nxt, bob3, rob3rta and arduino.
Fixes #1345 
This has been tested locally on my Windows 10 machine.

small improvements and corrections to various helptexts

---

OpenRobertaServer/staticResources/help/progHelp_mbot2_de.html
OpenRobertaServer/staticResources/help/progHelp_mbot2_en.html

Add help texts to robot system mbot 2

add helptexts for mbot 2 robot system

---

OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/nao/text_colours_functions.py
RobotNAO/src/main/java/de/fhg/iais/roberta/visitor/codegen/NaoPythonVisitor.java

Fixes wrong bracket placement for visistRgbColor visit-Method in the NAO python code generation.

Fixed bracket placement for colors in NAO code generation

---

OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/visitor/validate/DifferentialMotorValidatorAndCollectorVisitor.java

Added empty checker for curve blocks.
This affects every robot using the new differentialdriveValidator

Added empty checker for steer direction block

---

OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/mbot/actions.cpp
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/mbot/text_images_colours_messages_functions.cpp
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/nano33ble/action.cpp
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/nano33ble/text_colours_functions.cpp
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/sensebox/action.cpp
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/uno/action.cpp
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/uno/text_colours_functions.cpp
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/unowifirev2/action_1.cpp
OpenRobertaServer/src/test/resources/crossCompilerTests/_expected/robotSpecific/targetLanguage/unowifirev2/text_colours_functions.cpp
RobotArdu/src/main/java/de/fhg/iais/roberta/visitor/codegen/ArduinoCppVisitor.java
RobotArdu/src/main/java/de/fhg/iais/roberta/visitor/codegen/MbotCppVisitor.java
RobotArdu/src/main/java/de/fhg/iais/roberta/visitor/codegen/SenseboxCppVisitor.java

- update visitLightAction methods in Arduino, Mbot and Sensebox CPP visitors.
- update tests to accommodate changes.
The relevant changes for `arduino-resources` repo can be found [here](https://github.com/OpenRoberta/arduino-resources/pull/3).
Fixes #1331 
Tested with source code editor. Yet to be tested on the robots, hence **WIP**.

Issue #1331: fix server error when generating colour with user defined function

---

OpenRobertaServer/staticResources/js/app/roberta/controller/configuration.controller.js
OpenRobertaWeb/src/app/roberta/controller/configuration.controller.js

This PR fixes the issue that the language of the blocks in the configuration wasn't updated when changing it, while not being in the configuration view.

Issue #1069: language of blocks in configuration updates 
